rpm: &rpm
  tar: tar gzip
  specs: which findutils
  zlib: zlib-devel
  openssl: openssl-devel
  cext: gcc make
  c++: gcc-c++
  set-locale:
    - ENV LANG=en_US.UTF-8

deb: &deb
  locale: locales
  tar:
  specs: netbase
  zlib: libz-dev
  openssl: libssl-dev
  cext: gcc make
  c++: g++
  set-locale:
    # Uncomment the en_US.UTF-8 line in /etc/locale.gen
    - RUN sed -i '/en_US.UTF-8/s/^# //g' /etc/locale.gen
    # locale-gen generates locales for all uncommented locales in /etc/locale.gen
    - RUN locale-gen
    - ENV LANG=en_US.UTF-8

# Too old g++
#ol7:
#  base: oraclelinux:7-slim
#  install: RUN yum install -y
#  locale:
#  <<: *rpm

ol8:
  base: oraclelinux:8-slim
  install: RUN microdnf install -y
  locale: glibc-langpack-en
  <<: *rpm

ol9:
  base: oraclelinux:9-slim
  install: RUN microdnf install -y
  locale: glibc-langpack-en
  <<: *rpm

fedora37:
  base: fedora:37
  install: RUN dnf install -y
  locale: glibc-langpack-en
  <<: *rpm

fedora38:
  base: fedora:38
  install: RUN dnf install -y
  locale: glibc-langpack-en
  <<: *rpm

ubuntu1804:
  base: ubuntu:18.04
  install: RUN apt-get update && apt-get install -y
  <<: *deb

ubuntu2004:
  base: ubuntu:20.04
  install: RUN apt-get update && apt-get install -y
  <<: *deb

ubuntu2204:
  base: ubuntu:22.04
  install: RUN apt-get update && apt-get install -y
  <<: *deb

debian10:
  base: debian:10 # buster
  install: RUN apt-get update && apt-get install -y
  <<: *deb

debian11:
  base: debian:11 # bullseye
  install: RUN apt-get update && apt-get install -y
  <<: *deb

debian12:
  base: debian:12 # bookworm
  install: RUN apt-get update && apt-get install -y
  <<: *deb
